Ttree:
  Fusion:
    DocumentFinder:
      documentPrototype:
        fallback: Ttree.AfxWorkshop:Document.PageTemplate
        suffix: Template

Sitegeist:
  Monocle:
    viewportPresets:
      xs:
        label: 'xtra small'
        width: 400
        height: 600
      md:
        label: 'medium'
        width: 600
        height: 400
      l:
        label: 'wide'
        width: 800
        height: 600

Neos:
  Neos:
    userInterface:
      editPreviewModes:
        mobile:
          isEditingMode: false
          isPreviewMode: true
          fusionRenderingPath: ''
          title: 'Mobile'
          position: 200
          width: 400px
          height: 600px
        tablet:
          isEditingMode: false
          isPreviewMode: true
          fusionRenderingPath: ''
          title: 'Tablet'
          position: 210
          width: 800px
          height: 600px
