Ttree:
  Fusion:
    DocumentFinder:
      documentPrototype:
        fallback: Ttree.AfxWorkshop:Document.PageTemplate
        suffix: Template

Sitegeist:
  Monocle:
    viewportPresets:
      xs:
        label: 'xtra small'
        width: 400
        height: 600
      md:
        label: 'medium'
        width: 600
        height: 400
      l:
        label: 'wide'
        width: 800
        height: 600
